camera:
  ["FRONT", "FRONT_LEFT", "FRONT_RIGHT", "SIDE_LEFT", "SIDE_RIGHT"]

input:
  "/Users/wuyou/Works/universal_interface/input"

output:
  "/Users/wuyou/Works/universal_interface/test"

process:
  ego_pose: true
  camera: true