camera:
  ["FRONT", "FRONT_LEFT", "FRONT_RIGHT", "SIDE_LEFT", "SIDE_RIGHT"]

input:
  "/home/saimo/wuyou/universal_interface/input"

output:
  "/home/saimo/wuyou/universal_interface/test"

process:
  ego_pose: true
  camera: true
  track: true
  dynamic_mask: true